Use run_powershell_script method instead of powershell
This fixes "NoMethodError: undefined method `powershell'" with winrm 1.8

(https://github.com/WinRb/WinRM/blob/master/changelog.md#150)